version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.4.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: install virtualenv
          command: pip install virtualenv
      - run:
          name: setup virtualenv
          command: virtualenv .venv
      - run:
          name: sourcing virtualenv
          command: source .venv/bin/activate
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests for Backend
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_and_push:
    executor: docker/default
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/bookquest:latest .
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: docker push $DOCKERHUB_USERNAME/bookquest:latest

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - build_and_push:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
