version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - run:
        name: Checkout code
        command: git config --global credential.helper store;git clone https://janar363:${GITHUB_ACCESS_TOKEN}@github.com/janar363/BOOKQUEST.git
      - run: echo "hello world"
      - run:
          name: install virtualenv
          command: pip install virtualenv
      - run:
          name : setup virtualenv
          command: virtualenv .venv
      - run:
          name: sourcing virtualenv
          command: source .venv/bin/activate
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests for Backend
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build_and_test

