version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.4.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: install virtualenv
          command: pip install virtualenv
      - run:
          name: setup virtualenv
          command: virtualenv .venv
      - run:
          name: sourcing virtualenv
          command: source .venv/bin/activate
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests for Backend
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
